### ISSUE TITLE
Update task structure from honeybee

### ISSUE THREAD

**Issue by mostaphaRoudsari** [ladybug-tools/workerbee-dag#2]
Workflow > [task1: [subtak1, subtask2, ...] , task2: [subtak1, subtask2, ...] , task3: [subtak1, subtask2, ...]]

1. Each task in Workflow will be executed in serial and all subtasks in a task will be executed in parallel.
2. The results of each task can be directed directly to database.
3. Each subtask should report the progress during the execution.

**Comment by AntoineDao** [comment]
This looks a lot like a Direct Acyclic Graph ([DAG](https://www.astronomer.io/guides/dags/), and by looks a lot I mean it is. Have you looked into Apache Airlfow to draw some inspiration if these are meant to be run locally? I suspect that the abstraction provided by Workerbee will want to provide a similar way of writing workflows as Airflow if we want to then reproduce similar tasks on the cloud with minimal effort. 

Airflow will be great to run on servers but does not seem ideal to run locally so would not just implement it as such. However it might be worth giving [Luigi](https://github.com/spotify/luigi) and [Dagobah](https://github.com/thieman/dagobah) a quick look. I don't think you need to use the entire offering but these libraries will remove a lot of the work involved in saving results, abstracting connectors, adding re-run as an option and provide a fancy UI as well.

**Comment by mostaphaRoudsari** [comment]
Thanks! I have seen Airflow and Luigi. Didn't know about Dagobah!

Some of the tasks that we are running are so specific that I couldn't get my head around how to implement them with those libraries. They were also both quite heavy for what we needed but Dagobah looks like a option that we can use.

Let me push the first iteration to GitHub and then you tell me if it makes sense to go in the direction of using one of the DAG libraries.

Nice profile picture BTW. The new job is growing on you. ;P

**Comment by mostaphaRoudsari** [comment]
This is a good read: https://towardsdatascience.com/data-pipelines-luigi-airflow-everything-you-need-to-know-18dc741449b7
